# Generated by Django 6.0.3 on 2026-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings', 'Savings'), ('debt', 'Debt')], default='expense', max_length=10),
        ),
    ]
