# Generated by Django 6.0.3 on 2026-03-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transaction_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(help_text='Enter a specific category (e.g., Food, Travel, Rent, Salary).', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings', 'Savings'), ('debt', 'Debt')], default='expense', help_text='Select whether this is money coming in, going out, saved, or owed.', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Is this money coming in or going out?', max_length=7),
        ),
    ]
